apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - vm/namespace.yaml
  - vm/fedora-vm.yaml
  - testing/test-pods.yaml
  - network-policies/
  - network/

commonLabels:
  app.kubernetes.io/part-of: multi-network-demo
  app.kubernetes.io/managed-by: argocd