apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: br-ex-network
  namespace: default
  annotations:
    k8s.ovn.org/network-name: br-ex-network
spec:
  config: |
    {
      "name": "br-ex-network",
      "type": "ovn-k8s-cni-overlay",
      "cniVersion": "0.4.0",
      "topology": "localnet",
      "subnets": "172.16.87.0/24",
      "netAttachDefName": "default/br-ex-network"
    }