apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multi-network-policies-demo
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io/cleanup
spec:
  project: default
  source:
    repoURL: https://github.com/epheo/multi-network-policies-demo
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: multi-network-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true