apiVersion: k8s.cni.cncf.io/v1beta1
kind: MultiNetworkPolicy
metadata:
  name: br-ex-ssh-block-policy
  namespace: multi-network-demo
  annotations:
    k8s.v1.cni.cncf.io/policy-for: default/br-ex-network
spec:
  podSelector:
    matchLabels:
      app: fedora-demo
  policyTypes:
  - Ingress
  ingress:
  - from: []
    ports:
    - protocol: TCP
      port: 80
    - protocol: TCP
      port: 443
      